"use client";
import { useEffect, useState } from "react";
import { RequireAuth, inputClass } from "@/components/ui";
import MockInterviewEditor from "@/components/MockInterviewEditor";
import { listTopics } from "@/lib/questions";
import type { Topic } from "@/lib/types";
import { startInterview, finishInterview, interviewHistory, type Interview, type InterviewSession } from "@/lib/interview";
function InterviewFlow() {
 const [topics,setTopics]=useState<Topic[]>([]);const [topic,setTopic]=useState("");const [count,setCount]=useState(5);const [interview,setInterview]=useState<Interview|null>(null);const [busy,setBusy]=useState(false);const [answerBusy,setAnswerBusy]=useState(0);const [error,setError]=useState("");const [history,setHistory]=useState<InterviewSession[]>([]);const [page,setPage]=useState(1);const [pages,setPages]=useState(0);const [tick,setTick]=useState(0);const [historyError,setHistoryError]=useState("");
 useEffect(()=>{const ac=new AbortController();listTopics(ac.signal).then(t=>{if(!ac.signal.aborted){setTopics(t);setTopic(previous=>previous||t[0]?.id||"");}}).catch(e=>{if(!ac.signal.aborted)setError(e instanceof Error?e.message:"Không tải được topics");});return ()=>ac.abort();},[tick]);
 useEffect(()=>{const ac=new AbortController();interviewHistory(page,ac.signal).then(h=>{if(!ac.signal.aborted){setHistory(h.items);setPages(h.totalPages);setHistoryError("");}}).catch(e=>{if(!ac.signal.aborted)setHistoryError(e instanceof Error?e.message:"Không tải được lịch sử");});return ()=>ac.abort();},[page,tick]);
 async function start(){setBusy(true);setError("");try{setInterview(await startInterview(topic,count));setTick(t=>t+1);}catch(e){setError(e instanceof Error?e.message:"Không mở được phiên");}finally{setBusy(false);}}
 async function finish(){if(!interview)return;setBusy(true);setError("");try{const s=await finishInterview(interview.session.id);setInterview({...interview,session:s});setTick(t=>t+1);}catch(e){setError(e instanceof Error?e.message:"Không kết thúc được phiên");}finally{setBusy(false);}}
 const finished=interview?.session.status==="FINISHED";
 return <div className="space-y-6"><h1 className="font-display text-3xl">Mock Interview</h1><p className="text-ink-400">Trả lời bằng văn bản, nhận điểm từ khóa và đáp án tham khảo. Có thể sửa câu trả lời trước khi kết thúc.</p>{error&&<p role="alert" className="text-ember-400">{error} <button onClick={()=>setTick(t=>t+1)} className="underline">Tải lại</button></p>}
 {!interview||finished?<form onSubmit={e=>{e.preventDefault();void start();}} className="flex flex-wrap items-end gap-4"><label>Topic<select className={inputClass} value={topic} onChange={e=>setTopic(e.target.value)} required>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Số câu<input type="number" required min={1} max={20} value={count} onChange={e=>setCount(Number(e.target.value))} className={inputClass}/></label><button disabled={busy||!topic} className="rounded-sm bg-ember-500 px-5 py-3 text-ink-950 disabled:opacity-50">Bắt đầu</button></form>:null}
 {interview&&<>{finished&&<p className="font-display text-2xl">Điểm trung bình: {interview.session.overallScore}%</p>}{interview.questions.map(q=><MockInterviewEditor key={`${interview.session.id}:${q.questionId}`} sessionId={interview.session.id} question={q} disabled={busy||!!finished} onBusy={b=>setAnswerBusy(n=>n+(b?1:-1))}/>)}{!finished&&<button disabled={busy||answerBusy>0} onClick={()=>void finish()} className="rounded-sm bg-ember-500 px-5 py-3 text-ink-950 disabled:opacity-50">{busy?"Đang kết thúc…":"Kết thúc phỏng vấn"}</button>}</>}
 <section className="space-y-3 border-t border-ink-700 pt-6"><h2 className="font-display text-xl">Lịch sử phỏng vấn</h2>{historyError?<p role="alert">{historyError} <button onClick={()=>setTick(t=>t+1)}>Thử lại</button></p>:history.length===0?<p>Chưa có phiên phỏng vấn.</p>:history.map(s=><p key={s.id}>{new Date(s.startedAt).toLocaleString("vi-VN")} · {s.questionCount} câu · {s.status==="FINISHED"?`${s.overallScore}%`:"Đang làm"}</p>)}<div className="flex gap-4"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>← Trước</button><span>{page}/{Math.max(1,pages)}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Sau →</button></div></section></div>;
}
export default function MockInterviewPage(){return <RequireAuth><InterviewFlow/></RequireAuth>;}
