"use client";

import { useLocale } from "@/components/locale";
import { HCMUS_NOTICE, HUS_ADMISSIONS, type EnglishTrack } from "@/lib/english-preparation";

export function ExamPreparationGuide({ track, disabled, onChange }: { track: EnglishTrack; disabled: boolean; onChange: (track: EnglishTrack) => void }) {
  const { locale } = useLocale();
  const c = (vi: string, en: string) => locale === "vi" ? vi : en;
  return <section className="space-y-3 border-b border-line pb-5" aria-label={c("Chọn hướng ôn thi", "Choose an exam preparation track")}>
    <div className="flex flex-wrap items-center gap-3"><label htmlFor="english-track" className="font-medium text-strong">{c("Bạn đang ôn bài thi nào?", "Which examination are you preparing for?")}</label><select id="english-track" disabled={disabled} value={track} onChange={e => onChange(e.target.value as EnglishTrack)} className="min-h-12 w-full rounded-lg border border-control bg-surface px-3 text-base text-strong sm:w-auto"><option value="VSTEP">{c("VSTEP.3–5 / thi chứng chỉ", "VSTEP.3–5 / certificate examination")}</option><option value="HCMUS_PREPARATION">{c("Tiếng Anh đầu vào KHTN · ĐHQG-HCM", "HCMUS internal postgraduate English entrance")}</option></select></div>
    <p className="max-w-prose text-sm leading-relaxed text-body">{c("Bài tiếng Anh nội bộ KHTN–ĐHQG TP.HCM khác VSTEP. Chọn hướng ôn đúng trước khi dành nhiều thời gian cho email và essay.", "The internal HCMUS English entrance paper differs from VSTEP. Choose the right track before concentrating on emails and essays.")}</p>
    <details className="text-sm leading-relaxed text-body"><summary className="min-h-11 cursor-pointer py-3 font-medium text-accent">{c("Cấu trúc, nguồn chính thức và cách dùng phòng học", "Format, official sources and how to use the room")}</summary><div className="max-w-prose space-y-4 pt-2">
      {track === "HCMUS_PREPARATION" ? <>
        <p>{c("Đã đối chiếu Phụ lục 5 của thông báo tuyển sinh thạc sĩ đợt 2/2026, kiểm tra ngày 10/10/2026. Đây là hướng ôn tự biên soạn, không phải đề thi của trường hoặc bài thi thử đủ 100 điểm.", "Checked against Appendix 5 of the 2026 second-round master's admission notice on 10 October 2026. This is independently authored preparation, not an institution paper or a complete 100-point mock.")}</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>{c("Từ vựng & Đọc: 10 câu từ vựng + 10 câu đọc, 20 điểm.", "Vocabulary & Reading: 10 vocabulary + 10 reading questions, 20 points.")}</li>
          <li>{c("Grammar & Use of English Writing: 15 câu hoàn thành câu + 10 câu cloze + 5 câu biến đổi câu, 40 điểm. Không phải hai bài email/essay VSTEP.", "Grammar & Use of English Writing: 15 sentence completions + 10 cloze questions + 5 sentence transformations, 40 points. Not the two VSTEP email/essay tasks.")}</li>
          <li>{c("Nghe: 10 hội thoại ngắn + 5 câu hội thoại dài + 5 câu bài nói, 20 điểm.", "Listening: 10 short-conversation + 5 long-conversation + 5 talk questions, 20 points.")}</li>
          <li>{c("Nói: tự giới thiệu 5 điểm, hội thoại có hướng dẫn 15 điểm.", "Speaking: self-introduction worth 5 points and guided conversation worth 15.")}</li>
        </ul>
        <p>{c("Phụ lục ghi Đọc–Viết 90 phút, Nghe khoảng 20 phút, Nói khoảng 15 phút gồm chuẩn bị; đồng thời ghi thời lượng tối đa 120 phút gồm chuyển tiếp. Xác nhận lịch thực tế trên giấy báo thi, không suy ra tổng thời gian bằng cách cộng các mốc này.", "The appendix states 90 minutes for Reading–Writing, about 20 for Listening and about 15 for Speaking including preparation, alongside a 120-minute maximum including transitions. Confirm actual scheduling on your exam notice rather than adding these figures.")}</p>
        <p>{c("Ưu tiên hoàn thành câu, cloze và biến đổi câu; mỗi câu sai nên xem lý do rồi thử lại không nhìn mẫu. Thu âm tự giới thiệu bằng thông tin thật và tập câu hỏi tiếp nối. Bộ Nghe 20 câu tự biên soạn có đủ số câu theo cấu trúc 10 + 5 + 5; không phải đề thi trường hoặc bài đã hiệu chuẩn. Các đoạn Đọc/Nghe riêng dùng chung được gắn nhãn luyện kỹ năng chuyển giao.", "Prioritise sentence completion, cloze and transformations; review the explanation for a mistake, then try again without the model. Record an introduction using true details and practise follow-up questions. The original 20-question Listening set follows the 10 + 5 + 5 section counts; it is neither an institution paper nor a calibrated assessment. Shared individual Reading/Listening tasks are labelled transfer practice.")}</p>
        <p>{c("Trường công bố cấu trúc, không công bố danh sách chủ đề tiếng Anh chi tiết trong phụ lục này. Chủ đề học tập, công việc, đời sống ở đây là lựa chọn luyện tập, không phải dự đoán đề. Đừng nhầm Phụ lục 6 về phỏng vấn chuyên môn với phần Nói tiếng Anh.", "The appendix gives a format, not a detailed English topic bank. Study, work and daily-life topics here are practice choices, not exam predictions. Appendix 6 on subject-specific admission interviews is not the English Speaking syllabus.")}</p>
        <a href={HCMUS_NOTICE} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center font-medium text-accent underline underline-offset-4">{c("Thông báo KHTN–ĐHQG-HCM và các phụ lục (2026)", "HCMUS notice and appendices (2026)")}</a>
      </> : <>
        <p>{c("VSTEP.3–5: Nghe khoảng 40 phút/35 câu; Đọc 60 phút/40 câu; Viết 60 phút gồm thư/email ≥120 từ (1/3) và essay ≥250 từ (2/3); Nói 12 phút/3 phần. Bài mẫu hiện sau nộp. Bài ngắn là khởi động; bộ Nghe/Đọc đủ số phần và số câu vẫn chưa phải bài đánh giá đã hiệu chuẩn.", "VSTEP.3–5: Listening about 40 minutes/35 questions; Reading 60 minutes/40 questions; Writing 60 minutes with a letter/email of at least 120 words (one-third) and an essay of at least 250 (two-thirds); Speaking 12 minutes/three parts. Models appear after submission. Short tasks are warm-ups; complete Listening/Reading sets are not calibrated assessments.")}</p>
        <a href="https://vstep.vnu.edu.vn/test-format/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center font-medium text-accent underline underline-offset-4">{c("Định dạng VSTEP của ULIS–VNU", "ULIS–VNU VSTEP format")}</a>
      </>}
      <p>{c("Nếu bạn dự tuyển KHTN–ĐHQG Hà Nội: hướng dẫn đợt 2/2026 nêu minh chứng tiếng Anh bậc 3 trở lên hoặc văn bằng/VNU Test phù hợp. Không áp dụng cấu trúc thi nội bộ của KHTN TP.HCM cho trường này.", "For HUS–VNU Hanoi: the second-round 2026 guidance lists qualifying level-3-or-higher English evidence, degrees or VNU Test results. Do not apply the HCMUS internal examination format to HUS.")} <a href={HUS_ADMISSIONS} target="_blank" rel="noopener noreferrer" className="font-medium text-accent underline underline-offset-4">{c("Xem yêu cầu KHTN Hà Nội", "Read HUS requirements")}</a></p>
      <p className="text-subtle">{c("Kiểm tra đúng trường, đợt tuyển sinh và diện miễn thi. Số câu đúng trong phòng học không quy đổi thành điểm thi, điểm đỗ hoặc chứng chỉ.", "Check the institution, admission round and exemption route. Practice correct counts are not examination scores, pass decisions or certificates.")}</p>
    </div></details>
  </section>;
}
