/** Educational snapshot, not runtime configuration or production telemetry. */
export type Copy = readonly [vi: string, en: string];
export const BACKEND_REVISION = "b1d6c34af8438edcd60ad3f44b4858d56555ea5a";
export const FRONTEND_REVISION = "f41399e8c5dbc0ad968ffb7b1f992f63f89a43a5";
export const AUTH_SNAPSHOT = { accessMinutes: 15, refreshDays: 7, absoluteSessionDays: 30, oauthRequestSeconds: 300 } as const;
export const sourceUrl = (path: string, frontend = false) => `https://github.com/darkb2001/knowledge-gym${frontend ? "-frontend" : ""}/blob/${frontend ? FRONTEND_REVISION : BACKEND_REVISION}/${path}`;
export const diagramUrl = (slug: string) => `/blog/architecture-diagrams/${slug}.html`;

export const diagrams = [
  { id: "deployment", title: ["Triển khai & hạ tầng", "Deployment & infrastructure"], description: ["Theo request từ browser qua Cloudflare Tunnel, Nginx và một Spring Boot runtime đến các data services. Các dịch vụ quan sát có đường đọc riêng.", "Follow requests through Cloudflare Tunnel, Nginx and one Spring Boot runtime into data services. Observability has its own read path."] },
  { id: "layers", title: ["Module & Clean Architecture", "Modules & Clean Architecture"], description: ["Đây là dependency của code, không phải các microservice. Domain và ports ở lõi; adapter xử lý I/O; Boot lắp ghép tất cả thành một ứng dụng.", "These are code dependencies, not microservices. Domain and ports live in the core; adapters perform I/O; Boot composes one application."] },
  { id: "async", title: ["Outbox & dữ liệu tìm kiếm", "Outbox & search data"], description: ["Hai relay khác nhau: event_outbox phát Kafka; search_outbox cập nhật Elasticsearch. PostgreSQL vẫn là dữ liệu gốc, index là eventual-consistent read model.", "Two distinct relays: event_outbox publishes to Kafka; search_outbox updates Elasticsearch. PostgreSQL remains authoritative; the index is an eventually consistent read model."] },
  { id: "password", title: ["Đăng nhập bằng mật khẩu", "Password login"], description: ["Email → BCrypt → kiểm tra trạng thái tài khoản → phát hai JWT → lưu refresh hash vào PG/Redis → trả access trong JSON và refresh bằng cookie.", "Email → BCrypt → account checks → issue two JWTs → persist refresh hashes in PG/Redis → return access in JSON and refresh in a cookie."] },
  { id: "google", title: ["Đăng nhập Google OAuth2", "Google OAuth2 login"], description: ["Google xác minh danh tính; hệ thống phát JWT riêng của Knowledge Gym. Không dùng Google token làm Bearer cho API của app, không tự liên kết tài khoản LOCAL trùng email.", "Google verifies identity; Knowledge Gym issues its own JWTs. Google tokens are not app API bearer tokens, and matching LOCAL accounts are not silently linked."] },
  { id: "refresh", title: ["Refresh & vòng đời phiên", "Refresh & session lifetime"], description: ["Refresh trước khi hết hạn → đổi token nhưng giữ family → cookie mới có thêm 7 ngày, trong khi hạn tuyệt đối 30 ngày kể từ login đầu vẫn chặn. Nhánh reuse/blacklist thu hồi family bằng transaction riêng nên không bị rollback theo AuthException.", "Refresh before expiry → rotate within the same family → the new cookie gets another seven days, while a 30-day absolute cap from first login still applies. Reuse/blacklist branches revoke the family in a separate transaction so the AuthException does not roll it back."] },
  { id: "sessions", title: ["Thiết bị & thu hồi phiên", "Devices & revocation"], description: ["Mỗi login tạo refresh-token family mới. Thu hồi refresh theo family; access cutoff lại ở cấp user. IP/User-Agent giúp mô tả phiên, không chứng minh danh tính phần cứng.", "Each login creates a new refresh-token family. Refresh revocation is family-level; access cutoff is user-level. IP/User-Agent describe a session, not hardware identity."] },
] satisfies { id: string; title: Copy; description: Copy }[];

export const technologies: { name: string; role: Copy; tradeoff: Copy; source: string }[] = [
  { name: "Java 21 · Spring Boot 4.1.1", role: ["Một JVM chạy REST, DI, security và jobs; không phải cluster microservice.", "One JVM runs REST, DI, security and jobs; not a microservice cluster."], tradeoff: ["Deploy đơn giản; các module chia sẻ tài nguyên và blast radius.", "Simple deployment; modules share resources and blast radius."], source: "gradle/libs.versions.toml" },
  { name: "Gradle · Clean Architecture", role: ["Bốn module; ports tách business logic khỏi I/O. Domain không dùng Spring; application có compileOnly annotations.", "Four modules; ports separate business logic from I/O. Domain avoids Spring; application has compileOnly annotations."], tradeoff: ["ArchUnit kiểm tra dependency; không có nghĩa mọi code trong kg-core là pure Java.", "ArchUnit checks dependencies; not all kg-core code is pure Java."], source: "kg-core/build.gradle.kts" },
  { name: "PostgreSQL 16 · JPA / JDBC", role: ["Nguồn dữ liệu gốc: users, nội dung, lịch ôn, quiz, notes, blog, audit và outbox.", "Source of truth: users, content, reviews, quizzes, notes, blog, audit and outbox."], tradeoff: ["JPA cho entity; JDBC cho query/control chuyên biệt. DB down ảnh hưởng phần lớn app.", "JPA for entities; JDBC for specialized queries/control. DB downtime affects most features."], source: "kg-infrastructure/build.gradle.kts" },
  { name: "Flyway", role: ["Version hóa schema qua V001–V038; Hibernate validate thay vì tự sửa schema.", "Versions schema through V001–V038; Hibernate validates rather than mutating it."], tradeoff: ["Migration là nguồn chân lý schema, không phải ERD cũ trong tài liệu.", "Migrations are schema authority, not older documentation ERDs."], source: "kg-presentation/src/main/resources/application.yml" },
  { name: "Redis 7", role: ["Refresh lookup, blacklist, family-revoked, rate limit và các read model/cache.", "Refresh lookup, blacklist, revoked families, rate limiting and read-model/cache support."], tradeoff: ["Cache miss có PG fallback; Redis outage không được coi là đã có fail-open auth.", "Cache misses have PG fallback; Redis outages are not proven fail-open auth."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/security/RedisRefreshTokenCacheAdapter.java" },
  { name: "Elasticsearch 9.1.5", role: ["Index tìm kiếm câu hỏi, notes của caller và blog đã publish; cập nhật bằng search_outbox.", "Indexes questions, caller-owned notes and published blog; updated via search_outbox."], tradeoff: ["Read failure → PG full-text fallback; compose vẫn chờ ES healthy lúc startup.", "Read failures fall back to PG full-text; compose still waits for healthy ES at startup."], source: "kg-core/src/main/java/com/knowledgegym/search/application/GlobalSearchUseCase.java" },
  { name: "Kafka 3.8.1 · KRaft", role: ["Event bus cho blog.collected, blog.published và email khi bật tương ứng.", "Event bus for blog.collected, blog.published and email when enabled."], tradeoff: ["Single broker; không hứa HA hay exactly-once. Consumer phải chịu được redelivery.", "Single broker; no HA or exactly-once promise. Consumers must tolerate redelivery."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/blog/OutboxKafkaPublisher.java" },
  { name: "Garage 2.4.1 · AWS SDK v2", role: ["S3-compatible object store cho ảnh/avatar/export; server I/O dùng endpoint nội bộ.", "S3-compatible image/avatar/export storage; server I/O uses an internal endpoint."], tradeoff: ["Presigned URL phải ký bằng hostname public; giới hạn lifetime tối đa 15 phút.", "Presigned URLs need a public signing hostname; maximum lifetime is 15 minutes."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/storage/S3CompatibleStorageAdapter.java" },
  { name: "Spring Security · JJWT · BCrypt", role: ["Password hashing, app JWT, Google OAuth2, xác thực request và role hiện tại từ DB.", "Password hashing, app JWT, Google OAuth2, request authentication and current DB roles."], tradeoff: ["JWT ký, không mã hóa payload; access guard vẫn đọc DB mỗi request có bearer.", "JWTs are signed, not payload-encrypted; the access guard still reads DB per bearer request."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/security/JwtAuthenticationFilter.java" },
  { name: "Nginx 1.27 · Cloudflare Tunnel", role: ["Ingress duy nhất qua tunnel → loopback Nginx; rate/connection limits và forwarded headers.", "Ingress through tunnel → loopback Nginx; rate/connection limits and forwarded headers."], tradeoff: ["Data services không publish port; Docker network vẫn có egress.", "Data services do not publish ports; the Docker network still allows egress."], source: "infra/nginx.prod.conf" },
  { name: "Bucket4j · Turnstile", role: ["Rate limit ở app; Turnstile bảo vệ endpoint được cấu hình khi bật flag.", "App-level rate limiting; Turnstile protects configured endpoints when enabled."], tradeoff: ["Turnstile không thay thế auth; compose mặc định off và fail-open=true khi được bật.", "Turnstile is not auth; compose defaults it off, with fail-open=true when enabled."], source: "docker-compose.prod.yml" },
  { name: "OpenAI-compatible · Resilience4j", role: ["AI text writer dùng nguồn đã thu thập, timeout/retry/circuit breaker và budget jobs.", "AI text writer uses collected evidence, timeout/retry/circuit breakers and job budgets."], tradeoff: ["Provider/model tùy cấu hình; không có tool execution. Writer/collector mặc định off trong compose.", "Provider/model are configurable; no tool execution. Compose defaults writer/collector off."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/blog/OpenAiWriterAdapter.java" },
  { name: "SMTP · Email outbox", role: ["Mã xác minh email và reset password; Kafka email là tùy chọn.", "Email verification and password reset codes; Kafka email is optional."], tradeoff: ["Cần SMTP credentials và flags đúng; không suy ra email đã chạy trên production.", "Needs working SMTP credentials/flags; not proof production mail is running."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/email/EmailOutboxService.java" },
  { name: "Actuator · Prometheus · Grafana", role: ["Metrics qua Nginx allowlist, scrape 15s, dashboard; Alertmanager ở ops stack riêng.", "Metrics through Nginx allowlists, 15s scrape, dashboards; Alertmanager is a separate ops stack."], tradeoff: ["Không phải live status trên trang này. Remote-write offsite là cấu hình mẫu, không được mặc định coi là bật.", "This page is not live status. Offsite remote-write is a sample, not assumed enabled."], source: "infra/prometheus.yml" },
];

export const domains: { name: string; purpose: Copy; tables: string; source: string }[] = [
  { name: "identity", purpose: ["Đăng nhập, Google identity, email verification, password reset, role, session revoke.", "Login, Google identity, email verification, password reset, roles and session revocation."], tables: "users · refresh_tokens · registration_email_challenges · password_reset_codes · notification_preferences", source: "V001__create_users.sql" },
  { name: "content", purpose: ["Track → topic → module → question → option; lifecycle và visibility cho nội dung.", "Track → topic → module → question → option; content lifecycle and visibility."], tables: "content_tracks · topics · modules · questions · question_options", source: "V036__content_tracks.sql" },
  { name: "learning", purpose: ["SRS, flashcard, quiz và mock interview; lưu lịch ôn và attempt để có thể tiếp tục học.", "SRS, flashcards, quizzes and mock interviews; persisted review schedules and attempts."], tables: "srs_decks · srs_cards · study_attempts · quiz_sessions · quiz_session_questions · quiz_answers · interview_sessions · interview_answers", source: "V013__create_quiz_interview.sql" },
  { name: "progress", purpose: ["Tiến độ và read model tổng hợp; không coi cache/leaderboard là dữ liệu gốc.", "Progress and aggregate read models; cache/leaderboards are not authoritative data."], tables: "user_progress · user_badges · notifications · daily_challenge_assignments", source: "V004__create_srs_progress.sql" },
  { name: "notes / english", purpose: ["Ghi chú cá nhân và lịch sử luyện tiếng Anh; notes search giới hạn theo caller.", "Personal notes and English practice history; notes search is caller-scoped."], tables: "notes · english_attempts", source: "V038__english_practice.sql" },
  { name: "blog / knowledge intake", purpose: ["Collector, AI jobs, review/moderation, learning draft và materialization trước khi đưa vào thư viện.", "Collection, AI jobs, review/moderation, learning drafts and materialization into the library."], tables: "blog_posts · blog_comments · blog_views · blog_post_likes · collector_sources · collected_items · blog_generation_queue · agent_runs · blog_writer_settings · blog_draft_revisions · blog_writer_audit · blog_ai_budget_reservations · knowledge_goals · knowledge_intake_runs · knowledge_intake_audit · learning_content_drafts · learning_draft_audit · learning_draft_materializations", source: "V030__learning_content_drafts.sql" },
  { name: "search / shared", purpose: ["Outbox, cấu hình search runtime và audit. Đây là hạ tầng nhất quán/quan sát xuyên domain.", "Outboxes, runtime search settings and audit: cross-domain consistency/observability infrastructure."], tables: "event_outbox · search_outbox · search_runtime_settings · search_runtime_setting_audit · audit_logs", source: "V023__search_outbox.sql" },
  { name: "challenge schema", purpose: ["Schema có sẵn; sự tồn tại bảng không chứng minh code runner đã deploy hoặc sandbox đã sẵn sàng.", "Existing schema; table existence does not prove a deployed code runner or ready sandbox."], tables: "challenges · challenge_test_cases · code_submissions", source: "V012__create_challenges.sql" },
];

export const storage: { name: string; location: Copy; lifetime: Copy; meaning: Copy; source: string; frontend?: boolean }[] = [
  { name: "Access JWT", location: ["Biến module accessToken trong memory của từng tab", "Module variable accessToken, in each tab's memory"], lifetime: ["15 phút; mất khi reload", "15 minutes; lost on reload"], meaning: ["Bearer cho API. sub=user UUID, role, jti, iat, exp, iatMs. Ký bằng access secret; không có fid. DB role/blocked/cutoff mới là quyết định cuối.", "API bearer. sub=user UUID, role, jti, iat, exp, iatMs. Signed with the access secret; no fid. DB role/blocked/cutoff remain authoritative."], source: "lib/api-client.ts", frontend: true },
  { name: "Refresh JWT", location: ["Cookie refreshToken trên API host; HttpOnly", "HttpOnly refreshToken cookie on the API host"], lifetime: [`7 ngày kể từ mỗi lần phát hành; hạn tuyệt đối ${AUTH_SNAPSHOT.absoluteSessionDays} ngày kể từ login đầu của family`, `7 days from each issuance; a hard ${AUTH_SNAPSHOT.absoluteSessionDays}-day cap from the family's first login`], meaning: ["sub + fid + jti + iat + exp + fiatMs; secret khác access. Prod: Secure, SameSite=Strict, Path=/, không Domain nên host-only. FE gửi credentials:include; JavaScript không đọc token này.", "sub + fid + jti + iat + exp + fiatMs; a separate secret. Prod: Secure, SameSite=Strict, Path=/, no Domain so host-only. FE uses credentials:include; JS cannot read it."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/security/RefreshTokenCookie.java" },
  { name: "SHA-256 refresh hash", location: ["PostgreSQL refresh_tokens + Redis", "PostgreSQL refresh_tokens + Redis"], lifetime: ["Audit row expires_at; Redis keys có TTL", "Audit row expires_at; Redis keys have TTLs"], meaning: ["PG: user_id, token_hash, family_id, created_at, expires_at, revoked_at, replaced_by, IP, UA. Redis: rt:{hash}, rt:blacklist:{hash}, rt:revoked:{familyId}. Không lưu raw JWT ở hai store này.", "PG: user_id, token_hash, family_id, created_at, expires_at, revoked_at, replaced_by, IP, UA. Redis: rt:{hash}, rt:blacklist:{hash}, rt:revoked:{familyId}. Neither stores the raw refresh JWT."], source: "kg-infrastructure/src/main/resources/db/migration/V001__create_users.sql" },
  { name: "kg_oauth_req", location: ["API cookie, AES-GCM, HttpOnly, Secure, Lax", "API cookie, AES-GCM, HttpOnly, Secure, Lax"], lifetime: ["300 giây; xóa khi consume callback", "300 seconds; cleared when callback consumes it"], meaning: ["Giữ authorization request và state thay vì JSESSIONID. Có thể serialize code_verifier nếu Spring cung cấp; code này không tự chứng minh PKCE luôn được bật. Path theo context /api/v1.", "Stores the authorization request/state instead of JSESSIONID. Can serialize code_verifier if Spring supplies it; this code does not prove PKCE is always enabled. Context path /api/v1."], source: "kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/security/HttpCookieOAuth2AuthorizationRequestRepository.java" },
  { name: "kg_session · kg.user", location: ["FE cookie marker + sessionStorage user", "FE marker cookie + sessionStorage user"], lifetime: ["Marker Max-Age 7 ngày; user theo sessionStorage", "Marker Max-Age 7 days; user follows sessionStorage"], meaning: ["Chỉ hỗ trợ routing/display; có thể sửa ở client. Không phải credential hay quyền ADMIN. RequireAuth xác minh /users/me; API kiểm tra bearer + DB + method security.", "Routing/display hints, editable by the client. Not a credential or ADMIN authority. RequireAuth verifies /users/me; API checks bearer + DB + method security."], source: "lib/session-marker.ts", frontend: true },
  { name: "kg.logout-intent · kg_logout", location: ["localStorage + FE cookie + memory fence", "localStorage + FE cookie + memory fence"], lifetime: ["localStorage đến khi login thành công; cookie 7 ngày", "localStorage until successful login; cookie 7 days"], meaning: ["Cờ không bí mật chặn restore sau logout lỗi mạng. Login/register/OAuth thành công mới gỡ fence. Theme/locale cũng nằm ở localStorage, nhưng JWT không nằm ở đó.", "Non-secret flags block restoration after a network-failed logout. Successful login/register/OAuth removes the fence. Theme/locale also use localStorage, but JWTs do not."], source: "lib/api-client.ts", frontend: true },
];

/** A labeled teaching example; not the user's actual session or a background refresh timer. */
export function rollingSessionExample(refreshDays: readonly number[], nowDay: number) {
  let lastIssuedDay = 0;
  for (const day of [...refreshDays].sort((a, b) => a - b)) {
    if (day < 0 || day > nowDay || day >= lastIssuedDay + AUTH_SNAPSHOT.refreshDays) continue;
    lastIssuedDay = day;
  }
  // Hạn tuyệt đối chặn rolling TTL: dù luôn refresh đúng hạn, phiên vẫn chết ở mốc này.
  const expiresDay = Math.min(lastIssuedDay + AUTH_SNAPSHOT.refreshDays, AUTH_SNAPSHOT.absoluteSessionDays);
  return { lastIssuedDay, expiresDay, expired: nowDay >= expiresDay };
}
