import { apiRequest } from "./api-client";
import type { PageResponse } from "./types";
export type QuizStrategy = "RANDOM" | "WEAKNESS" | "INTERVIEW" | "SPACED";
export type QuizQuestion = { questionId: string; title: string; options: { id: string; content: string }[] };
export type QuizSummary = { id: string; strategy: QuizStrategy; score: number | null; total: number; startedAt: string; finishedAt: string | null };
export type Quiz = QuizSummary & { questions: QuizQuestion[]; timeLimit: number };
export type QuizResult = { sessionId: string; score: number; correctCount: number; total: number; breakdown: { questionId: string; correct: boolean; selectedOptionId: string | null; correctOptionId: string | null }[] };
export const generateQuiz = (moduleId: string, count: number, strategy: QuizStrategy, difficulty?: string) => apiRequest<Quiz>("/quiz/generate", { method: "POST", body: { moduleId, count, strategy, difficulty: difficulty || undefined } });
export const submitQuiz = (id: string, answers: { questionId: string; selectedOptionId: string | null }[]) => apiRequest<QuizResult>(`/quiz/${encodeURIComponent(id)}/submit`, { method: "POST", body: { answers } });
export const quizHistory = (page = 1, signal?: AbortSignal, size = 10) => apiRequest<PageResponse<QuizSummary>>(`/quiz/history?page=${page}&size=${[5, 10, 20].includes(size) ? size : 10}`, { signal });
