"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import { ArrowSquareOutIcon, GitBranchIcon } from "@phosphor-icons/react";
import { useAdminCopy } from "./shared";
import { AUTH_SNAPSHOT, BACKEND_REVISION, FRONTEND_REVISION, diagrams, diagramUrl, domains, rollingSessionExample, sourceUrl, storage, technologies, type Copy } from "@/lib/architecture";

function Section({ id, title, intro, children }: { id: string; title: string; intro?: string; children: ReactNode }) {
  return <section id={id} aria-labelledby={`${id}-title`} className="scroll-mt-8 border-t border-line pt-8 sm:pt-10">
    <h2 id={`${id}-title`} className="text-xl font-semibold tracking-tight text-strong sm:text-2xl">{title}</h2>
    {intro && <p className="mt-3 max-w-[72ch] text-sm leading-7 text-body">{intro}</p>}
    <div className="mt-6">{children}</div>
  </section>;
}

function Source({ path, frontend = false, children }: { path: string; frontend?: boolean; children: ReactNode }) {
  return <a href={sourceUrl(path, frontend)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 text-sm text-accent underline underline-offset-4 hover:text-accent-hover">{children}<ArrowSquareOutIcon size={15} aria-hidden /></a>;
}

function DiagramExplorer() {
  const { c, locale } = useAdminCopy();
  const copy = (value: Copy) => value[locale === "en" ? 1 : 0];
  const [selected, setSelected] = useState("deployment");
  const diagram = diagrams.find(item => item.id === selected) ?? diagrams[0];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3">
      <label className="block w-full text-sm font-medium text-strong sm:w-auto">
        <span className="mb-2 block">{c("Chọn sơ đồ để khám phá", "Choose a diagram to explore")}</span>
        <select className="kg-field w-full sm:min-w-80" value={selected} onChange={event => setSelected(event.target.value)}>
          {diagrams.map(item => <option key={item.id} value={item.id}>{copy(item.title)}</option>)}
        </select>
      </label>
      <a href={diagramUrl(diagram.id)} target="_blank" rel="noopener noreferrer" className="kg-secondary gap-2">{c("Mở diagram rộng", "Open full diagram")}<ArrowSquareOutIcon size={18} aria-hidden /></a>
    </div>
    <p className="my-4 max-w-[75ch] text-sm leading-7 text-body" aria-live="polite">{copy(diagram.description)}</p>
    <div className="overflow-hidden rounded-xl border border-line bg-surface">
      <iframe key={diagram.id} title={copy(diagram.title)} src={diagramUrl(diagram.id)} loading="lazy" allowFullScreen sandbox="allow-scripts allow-downloads allow-popups" className="block h-[760px] w-full border-0 sm:h-[850px]" />
    </div>
    <p className="mt-3 text-xs leading-6 text-subtle">{c("Diagram do Archify dựng từ source đã ghim revision. Nhãn kỹ thuật giữ nguyên; viewer dùng control tiếng Anh, có zoom/theme/export. Chỉ tải một diagram mỗi lần. Nếu khung không tải, dùng “Mở diagram rộng”.", "Archify diagrams use revision-pinned source. Diagram annotations are Vietnamese; viewer controls are English, with zoom/theme/export. Only one diagram loads at a time. If the frame fails, use “Open full diagram”.")}</p>
  </div>;
}

function LifetimeExample() {
  const { c } = useAdminCopy();
  const [scenario, setScenario] = useState("active");
  const days = scenario === "active" ? [6, 12, 18] : [];
  const result = rollingSessionExample(days, 20);
  const events = [{ day: 0, action: c("Login → R0", "Login → R0"), expires: 7 }, ...days.map((day, index) => ({ day, action: c(`Refresh → R${index + 1}`, `Refresh → R${index + 1}`), expires: day + 7 }))];
  return <div>
    <label className="block max-w-md text-sm font-medium text-strong"><span className="mb-2 block">{c("Thử hai tình huống minh họa", "Compare two illustrative scenarios")}</span><select className="kg-field w-full" value={scenario} onChange={event => setScenario(event.target.value)}><option value="active">{c("Refresh thành công ngày 6, 12, 18", "Successful refresh on days 6, 12, 18")}</option><option value="idle">{c("Login rồi không refresh lần nào", "Login with no subsequent refresh")}</option></select></label>
    <ol className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label={c("Timeline minh họa, không phải phiên thật", "Illustrative timeline, not a real session")}>
      {events.map(event => <li key={event.day} className="border-b border-line pb-4"><p className="text-sm text-subtle">{c(`Ngày ${event.day}`, `Day ${event.day}`)}</p><p className="mt-1 font-medium text-strong">{event.action}</p><p className="mt-2 text-sm leading-6 text-body">{c(`Token này hết hạn ngày ${event.expires}.`, `This token expires on day ${event.expires}.`)}</p></li>)}
    </ol>
    <p className="mt-5 rounded-xl bg-accent-soft p-4 text-sm leading-7 text-strong" role="status">{result.expired ? c("Ở ngày 20: refresh token đã hết hạn từ ngày 7. Muốn truy cập API bảo vệ cần đăng nhập lại.", "On day 20: the refresh token expired on day 7. Protected API access requires signing in again.") : c("Ở ngày 20: R3 vẫn còn hạn đến ngày 25. Không cần login lại dù lần login đầu đã cách 20 ngày.", "On day 20: R3 is valid until day 25. No login is needed even though the original login was 20 days ago.")}</p>
    <p className="mt-3 text-xs leading-6 text-subtle">{c("Ví dụ chỉ mô phỏng lần refresh thành công trước hạn; app không có timer refresh mỗi 6 ngày. Access 15 phút khiến refresh xảy ra khi cần request/khôi phục phiên, không phải mỗi lần click. Mốc chính xác còn phụ thuộc exp, cookie và clock skew; ví dụ làm tròn theo ngày.", "This models successful refresh before expiry; the app has no six-day refresh timer. The 15-minute access token triggers refresh as requests/restoration need it, not on every click. Actual timing depends on exp, cookie expiry and clock skew; this example rounds to days.")}</p>
  </div>;
}

export function ArchitectureWorkspace() {
  const { c, locale } = useAdminCopy();
  const copy = (value: Copy) => value[locale === "en" ? 1 : 0];
  return <div className="space-y-10 sm:space-y-12">
    <div className="kg-panel">
      <div className="flex items-start gap-3"><GitBranchIcon size={24} className="mt-1 shrink-0 text-accent" aria-hidden /><div><h2 className="text-lg font-semibold text-strong">{c("Sau một tuần vẫn chưa cần login lại? Điều này có thể đúng.", "Still signed in after a week? That can be expected.")}</h2><p className="mt-3 max-w-[75ch] text-sm leading-7 text-body">{c("15 phút là tuổi thọ access token, không phải tuổi thọ phiên đăng nhập. Refresh token sống 7 ngày nhưng mỗi lần rotation thành công lại phát token mới sống thêm 7 ngày. Với rolling session hiện tại, dùng web đều có thể giữ phiên lâu hơn một tuần. Đây là kết luận từ code, chưa phải kiểm chứng phiên của bạn trên production.", "15 minutes is the access-token lifetime, not the login-session lifetime. A refresh token lasts seven days, but each successful rotation issues a fresh seven-day token. Regular use can keep this rolling session alive beyond a week. This is a code-derived explanation, not verification of your production session.")}</p><a href="#session-lifetime" className="mt-2 inline-flex min-h-11 items-center text-sm font-medium text-accent underline underline-offset-4">{c("Xem timeline và cách tự kiểm chứng", "See the timeline and verification steps")}</a></div></div>
    </div>

    <nav aria-label={c("Mục lục kiến trúc", "Architecture contents")} className="flex flex-wrap gap-x-6 gap-y-1 border-y border-line py-3 text-sm">
      {[["system-diagrams", c("Diagram", "Diagrams")], ["technical-roles", c("Vai trò kỹ thuật", "Technical roles")], ["domain-map", c("Domain & dữ liệu", "Domains & data")], ["token-storage", c("Auth & token", "Auth & tokens")], ["session-lifetime", c("Vòng đời phiên", "Session lifetime")], ["device-sessions", c("Thiết bị & quyền", "Devices & permissions")], ["source-evidence", c("Source & giới hạn", "Sources & limits")]].map(([id, label]) => <a key={id} href={`#${id}`} className="inline-flex min-h-11 items-center text-accent underline-offset-4 hover:underline">{label}</a>)}
    </nav>

    <Section id="system-diagrams" title={c("Hệ thống, từ tổng thể đến từng luồng", "The system, from overview to individual flows")} intro={c("Một modular monolith, nhiều adapter và data services. Chọn một góc nhìn thay vì nhồi mọi chi tiết vào một sơ đồ không thể đọc.", "One modular monolith, multiple adapters and data services. Choose a focused view instead of forcing every detail into one unreadable diagram.")}><DiagramExplorer /></Section>

    <Section id="technical-roles" title={c("Mỗi công nghệ đảm nhiệm điều gì?", "What does each technology own?")} intro={c("Phiên bản lấy từ manifest/compose hiện tại, không từ README cũ (README vẫn ghi Spring Boot 3.2). Cấu hình deploy không chứng minh service đang bật hay healthy.", "Versions come from current manifests/compose, not the older README (which still says Spring Boot 3.2). Deployment configuration does not prove a service is enabled or healthy.")}>
      <div className="divide-y divide-line">{technologies.map(item => <article key={item.name} className="grid gap-3 py-5 first:pt-0 md:grid-cols-[minmax(160px,0.7fr)_minmax(0,2fr)]"><h3 className="text-base font-semibold text-strong">{item.name}</h3><div className="min-w-0"><p className="max-w-[72ch] text-sm leading-7 text-body">{copy(item.role)}</p><p className="mt-2 max-w-[72ch] text-sm leading-7 text-subtle"><span className="font-medium">{c("Đánh đổi: ", "Trade-off: ")}</span>{copy(item.tradeoff)}</p><Source path={item.source}>{c("Đọc implementation", "Read implementation")}</Source></div></article>)}</div>
      <p className="mt-5 text-sm leading-7 text-body">{c("Frontend riêng: Next.js 15.5.27, React 19.3.0, TypeScript và Tailwind 3. App dùng fetch trực tiếp đến API host, không có BFF giữ refresh token thay browser trong luồng hiện tại.", "Separate frontend: Next.js 15.5.27, React 19.3.0, TypeScript and Tailwind 3. The current app fetches the API host directly; no BFF holds refresh tokens on behalf of the browser.")}</p><Source path="package.json" frontend>{c("Frontend manifest", "Frontend manifest")}</Source>
    </Section>

    <Section id="domain-map" title={c("Domain và nơi dữ liệu được lưu", "Domains and where data lives")} intro={c("Danh mục theo code và migrations; không phải full ERD từng cột. Trục chính: content_tracks → topics → modules → questions → question_options; users liên kết với refresh_tokens và các dữ liệu học cá nhân qua user_id.", "A code/migration inventory, not a column-level ERD. Main hierarchy: content_tracks → topics → modules → questions → question_options; users link to refresh_tokens and personal learning data through user_id.")}>
      <div className="divide-y divide-line">{domains.map(domain => <details key={domain.name} className="py-3"><summary className="min-h-11 cursor-pointer py-3 font-medium text-strong">{domain.name}</summary><div className="pb-3 pl-5"><p className="max-w-[72ch] text-sm leading-7 text-body">{copy(domain.purpose)}</p><p className="mt-3 break-words font-mono text-xs leading-7 text-subtle">{domain.tables}</p><Source path={`kg-infrastructure/src/main/resources/db/migration/${domain.source}`}>{c("Migration tham chiếu", "Reference migration")}</Source></div></details>)}</div>
      <p className="mt-5 text-sm leading-7 text-subtle">{c("DB giữ tính đúng; Redis là fast lookup/cache; ES là projection; Garage giữ bytes của object, không thay relational DB. event_outbox giúp giữ event bền qua lỗi broker, nhưng việc nhận lại event vẫn có thể lặp. AI queue trong PG giữ trạng thái job/budget, cần review trước khi công bố nội dung.", "DB owns correctness; Redis is fast lookup/cache; ES is a projection; Garage stores object bytes, not relational state. event_outbox durably retains events across broker failures, but redelivery can repeat. The PG AI queue tracks jobs/budgets; publication still needs review.")}</p>
    </Section>

    <Section id="token-storage" title={c("Authentication, authorization và từng loại token", "Authentication, authorization and each token type")} intro={c("Authentication trả lời “bạn là ai?”; authorization trả lời “bạn được làm gì?”. Google OAuth2 là một cách chứng minh identity, không thay thế role/ownership checks trong API của Knowledge Gym.", "Authentication asks who you are; authorization asks what you may do. Google OAuth2 proves identity; it does not replace app API role/ownership checks.")}>
      <div className="divide-y divide-line">{storage.map(item => <article key={item.name} className="py-5 first:pt-0"><h3 className="font-semibold text-strong">{item.name}</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-[120px_minmax(0,1fr)]"><dt className="text-subtle">{c("Lưu ở đâu", "Location")}</dt><dd className="leading-7 text-body">{copy(item.location)}</dd><dt className="text-subtle">{c("Thời hạn", "Lifetime")}</dt><dd className="leading-7 text-body">{copy(item.lifetime)}</dd><dt className="text-subtle">{c("Vai trò", "Purpose")}</dt><dd className="max-w-[75ch] break-words leading-7 text-body">{copy(item.meaning)}</dd></dl><Source path={item.source} frontend={item.frontend}>{c("Source lưu trữ", "Storage source")}</Source></article>)}</div>
      <details className="mt-6 rounded-xl border border-line p-4"><summary className="min-h-11 cursor-pointer py-2 font-medium text-strong">{c("Vì sao Strict cookie vẫn dùng được giữa FE và API?", "Why does a Strict cookie work between FE and API?")}</summary><p className="mt-3 max-w-[75ch] text-sm leading-7 text-body">{c("app.darkb-tech.io.vn và api.darkb-tech.io.vn là khác origin nhưng cùng site khi đều dùng HTTPS. SameSite kiểm tra site; CORS kiểm tra origin. Cookie refresh host-only chỉ gửi đến API; fetch dùng credentials:include, API allow đúng FE origin và allowCredentials=true. kg_oauth_req dùng Lax vì callback GET đến từ Google là cross-site. CSRF đang disabled trong SecurityConfig; Strict cookie là một lớp bảo vệ, không chứng nhận miễn nhiễm CSRF/XSS hoặc subdomain compromise.", "app.darkb-tech.io.vn and api.darkb-tech.io.vn are different origins but the same site over HTTPS. SameSite checks site; CORS checks origin. Host-only refresh cookies go to the API; fetch uses credentials:include and the API allows the specific FE origin plus credentials. kg_oauth_req is Lax for the cross-site GET callback from Google. SecurityConfig disables CSRF; Strict is one defense, not a certification against CSRF/XSS or subdomain compromise.")}</p><Source path="kg-presentation/src/main/resources/application-prod.yml">{c("Production cookie policy", "Production cookie policy")}</Source></details>
    </Section>

    <Section id="session-lifetime" title={c("7 ngày của token ≠ 7 ngày của toàn bộ phiên", "Seven token days ≠ seven session days")} intro={c(`Access hết hạn sau ${AUTH_SNAPSHOT.accessMinutes} phút. FE refresh khi access hết hạn trước request, khi restore sau reload, hoặc sau 401 rồi retry một lần. Không có refresh chạy mãi khi bạn không dùng app.`, `Access expires after ${AUTH_SNAPSHOT.accessMinutes} minutes. FE refreshes before requests with expired access, on restoration after reload, or after a 401 followed by one retry. There is no endless refresh while the app is unused.`)}>
      <LifetimeExample />
      <h3 className="mt-8 font-semibold text-strong">{c("Khi nào phải login lại?", "When must you sign in again?")}</h3>
      <ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-body"><li>{c("Refresh JWT/cookie hết hạn, bị xóa hoặc browser chặn cookie; không thể đổi access mới.", "Refresh JWT/cookie expired, was deleted or was blocked by the browser; new access cannot be obtained.")}</li><li>{c("Family của phiên bị revoke, logout, reset password hoặc admin cắt phiên; account blocked. Change password giữ family hiện tại khi nhận diện được cookie, revoke các family khác.", "The session family is revoked, logout/password reset/admin revocation occurs, or the account is blocked. Password changes preserve the current family when its cookie can be identified and revoke other families.")}</li><li>{c("Refresh bị server từ chối với 401/403. Lỗi network/5xx/429 không tự chứng minh phiên đã chết; FE giữ trạng thái và báo lỗi/retry.", "The server rejects refresh with 401/403. Network/5xx/429 failures do not establish session death; FE preserves state and surfaces retryable errors.")}</li></ul>
      <h3 className="mt-8 font-semibold text-strong">{c("Tự kiểm chứng trên trình duyệt đang dùng", "Verify in your current browser")}</h3>
      <ol className="mt-3 list-decimal space-y-3 pl-5 text-sm leading-7 text-body"><li>{c("DevTools → Network → lọc /auth/refresh. Reload trang hoặc thực hiện request sau khi access hết hạn; quan sát POST 200 và Set-Cookie. Không copy/share token hay HAR chưa redact.", "DevTools → Network → filter /auth/refresh. Reload or request after access expiry; inspect POST 200 and Set-Cookie. Never share tokens or unredacted HAR files.")}</li><li>{c("Application → Cookies → API host → refreshToken: xem HttpOnly, Secure, SameSite và Expires/Max-Age. So sánh hạn cookie trước/sau refresh; JS phía FE không đọc được giá trị này.", "Application → Cookies → API host → refreshToken: inspect HttpOnly, Secure, SameSite and Expires/Max-Age. Compare cookie expiry before/after refresh; FE JavaScript cannot read its value.")}</li><li>{c("Profile → phiên đăng nhập: family giữ nguyên qua rotation. “Last seen” lấy thời điểm refresh row, không phải activity heartbeat. Một cookie kg_session=1 hay avatar còn hiển thị chưa chứng minh API session sống.", "Profile → sessions: the family persists through rotation. Last seen comes from refresh rows, not an activity heartbeat. A kg_session=1 cookie or visible avatar does not prove a live API session.")}</li></ol>
      <div className="mt-5 flex flex-wrap gap-x-5"><Source path="kg-core/src/main/java/com/knowledgegym/identity/application/RefreshTokenUseCase.java">{c("Rotation backend", "Backend rotation")}</Source><Source path="lib/api-client.ts" frontend>{c("Refresh/retry frontend", "Frontend refresh/retry")}</Source><Link href="/profile" className="inline-flex min-h-11 items-center text-sm text-accent underline underline-offset-4">{c("Mở hồ sơ & phiên đăng nhập", "Open profile & sessions")}</Link></div>
    </Section>

    <Section id="device-sessions" title={c("“Thiết bị” thực chất là một phiên browser", "A “device” is really a browser session")}>
      <div className="space-y-5 text-sm leading-7 text-body">
        <p className="max-w-[75ch]">{c("Mỗi login thành công sinh familyId UUID mới. Refresh đổi jti/hash nhưng giữ fid. IP và User-Agent được cập nhật theo request để hiển thị mô tả, không dùng làm khóa authentication, không ràng buộc fingerprint phần cứng. Hai tab cùng browser thường dùng chung refresh cookie; hai browser/profile có thể là hai family dù cùng máy.", "Each successful login creates a new familyId UUID. Refresh changes jti/hash but preserves fid. IP and User-Agent are request metadata, not authentication keys or hardware fingerprints. Two tabs usually share the refresh cookie; two browsers/profiles can have separate families on one machine.")}</p>
        <p className="max-w-[75ch]">{c("GET /auth/sessions nhóm các refresh row chưa revoked/chưa expired theo family_id. current so với fid trong cookie của caller; revoke chỉ cho family thuộc user đang xác thực. Query hiện tại tính MIN/MAX(created_at) trên active rows, vì vậy createdAt có thể là row active mới nhất chứ không phải thời điểm login gốc; lastSeen không phải thời điểm mọi API request.", "GET /auth/sessions groups unrevoked, unexpired refresh rows by family_id. current compares against the caller cookie's fid; revocation requires an owned family. MIN/MAX(created_at) currently consider active rows, so createdAt may reflect the latest active row rather than the original login; lastSeen is not every API request's timestamp.")}</p>
        <p className="max-w-[75ch]">{c("Logout/revoke có hai lớp: PG + Redis cắt refresh family; users.tokens_invalid_before cắt access ở cấp user. Vì access JWT không có fid, token access cũ của các thiết bị khác cũng có thể nhận 401; refresh family của chúng vẫn sống nên có thể lấy access mới. iatMs tránh sai lệch độ phân giải giây khi so cutoff.", "Logout/revoke has two layers: PG + Redis revoke the refresh family; users.tokens_invalid_before invalidates access at user level. Access JWTs have no fid, so other devices' old access tokens may also get 401; their refresh families survive and can obtain new access. iatMs avoids second-resolution cutoff ambiguity.")}</p>
        <p className="max-w-[75ch]">{c("Quyền không lấy từ kg.user do client sửa được. JwtAuthenticationFilter verify chữ ký/exp, JdbcAccessTokenGuard đọc role/blocked/cutoff thật từ DB rồi tạo ROLE_*. Admin API dùng @PreAuthorize(hasRole('ADMIN')); dữ liệu cá nhân còn cần ownership. USER/PREMIUM/ADMIN tồn tại trong model, nhưng không suy ra mọi tính năng PREMIUM đều đã được enforce.", "Permissions do not come from editable kg.user. JwtAuthenticationFilter verifies signature/exp; JdbcAccessTokenGuard reads actual DB role/blocked/cutoff and creates ROLE_*. Admin APIs use @PreAuthorize(hasRole('ADMIN')); personal data still needs ownership. USER/PREMIUM/ADMIN exist in the model, but that does not establish enforcement of every PREMIUM feature.")}</p>
      </div>
      <div className="mt-4 flex flex-wrap gap-x-5"><Source path="kg-core/src/main/java/com/knowledgegym/identity/application/SessionManagementUseCase.java">{c("Session management", "Session management")}</Source><Source path="kg-infrastructure/src/main/java/com/knowledgegym/infrastructure/persistence/adapter/JdbcSessionRegistryAdapter.java">{c("Query phiên thật", "Session query")}</Source><Source path="kg-presentation/src/main/java/com/knowledgegym/presentation/rest/admin/AdminUsersController.java">{c("Admin authorization", "Admin authorization")}</Source></div>
    </Section>

    <Section id="source-evidence" title={c("Bản đồ có bằng chứng, không phải lời hứa", "An evidence-backed map, not a promise")}>
      <dl className="grid gap-2 text-sm sm:grid-cols-[140px_minmax(0,1fr)]"><dt className="text-subtle">Backend snapshot</dt><dd className="break-all font-mono text-xs leading-6 text-body">{BACKEND_REVISION}</dd><dt className="text-subtle">Frontend snapshot</dt><dd className="break-all font-mono text-xs leading-6 text-body">{FRONTEND_REVISION}</dd></dl>
      <p className="mt-4 max-w-[75ch] text-sm leading-7 text-body">{c("Trang này là tài liệu đọc, không thực hiện mutation, không đọc/hiển thị token hoặc secret của bạn và không truy vấn production health. Diagram là asset tài liệu công khai từ repo công khai (có thể mở URL độc lập); chỉ page/workspace dùng RequireAdmin. Không xem client guard hay middleware marker là bảo vệ bí mật.", "This is read-only documentation: no mutations, no reading/displaying your tokens or secrets, and no production health queries. Diagrams are public documentation assets from public repositories and can be opened independently; the page/workspace uses RequireAdmin. Client guards and middleware markers are not confidentiality boundaries.")}</p>
      <h3 className="mt-6 font-semibold text-strong">{c("Giới hạn cần biết trước khi đánh giá bảo mật", "Limits to know before assessing security")}</h3>
      <ul className="mt-3 list-disc space-y-3 pl-5 text-sm leading-7 text-body"><li>{c("refreshInFlight là biến module: gộp request trong cùng tab, không có cross-tab lock. Multi-tab vẫn có thể reuse token cũ; không gọi mọi 401 là token bị đánh cắp.", "refreshInFlight is module state: coalesces within one tab, with no cross-tab lock. Multiple tabs can still reuse an old token; not every 401 means theft.")}</li><li>{c("Nhánh reuse trong RefreshTokenUseCase gọi revokeFamily rồi ném AuthException trong @Transactional. Cần kiểm chứng rollback/commit ở integration test trước khi hứa family revoke bền vững; diagram biểu diễn ý định branch, không chứng nhận hiệu lực production.", "Reuse branches call revokeFamily and then throw AuthException inside @Transactional. Verify rollback/commit in integration tests before promising durable family revocation; diagrams describe branch intent, not production certification.")}</li><li>{c("Redis cache miss khác Redis unavailable: PG fallback vẫn phải ghi/đọc lại Redis. Repo không có absolute family expiry; nếu muốn buộc login sau 7/30 ngày kể từ login đầu, đó là thay đổi policy/backend riêng, chưa được thực hiện ở đây.", "A Redis miss differs from Redis unavailability: PG fallback still writes/reads Redis. There is no absolute family expiry; forcing login after 7/30 days from original login needs a separate policy/backend change, not performed here.")}</li></ul>
    </Section>
  </div>;
}
